"""Verify the accuracy of the checkout report generated by another agent.

Usage:
    uv run verify_checkout_report.py
"""

import csv
import sys
from pathlib import Path
from datetime import datetime
from folio_client import get_client

REPORTS_DIR = Path("reports")

def get_latest_report() -> Path:
    """Find the most recent checkout report in the reports directory."""
    if not REPORTS_DIR.exists():
        return None
    files = list(REPORTS_DIR.glob("checkouts_*.csv"))
    if not files:
        return None
    return max(files, key=lambda f: f.stat().st_mtime)

def fetch_log_data(fc, limit=50) -> list[dict]:
    """Fetch recent checkout logs independently for verification."""
    result = fc.folio_get(
        "/audit-data/circulation/logs",
        key="logRecords",
        query_params={
            "query": 'action=="Checked out"',
            "limit": limit,
            "offset": 0,
        },
    )
    return result or []

def verify_report(report_path: Path):
    """Run verification against FOLIO API."""
    print(f"--- Verifying report: {report_path.name} ---")
    
    fc = get_client()
    
    # 1. Read the report
    with report_path.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        report_rows = list(reader)
    
    print(f"Report has {len(report_rows)} rows.")
    
    # 2. Fetch logs independently
    logs = fetch_log_data(fc, limit=max(len(report_rows) + 5, 50))
    print(f"Fetched {len(logs)} independent log entries from FOLIO.")
    
    # 3. Create a lookup for logs by timestamp (since timestamps should be unique-ish)
    # Note: Multiple events could happen in the same second, so we use a list
    log_lookup = {}
    for log in logs:
        ts = log.get("date")
        if ts not in log_lookup:
            log_lookup[ts] = []
        log_lookup[ts].append(log)
    
    # 4. Verification loop
    errors = []
    matches = 0
    
    for i, row in enumerate(report_rows):
        ts = row["timestamp"]
        title = row["title"]
        
        if ts not in log_lookup:
            errors.append(f"Row {i+1}: Timestamp '{ts}' not found in latest FOLIO logs.")
            continue
        
        # Check if any log at this timestamp matches the title
        found_match = False
        for log in log_lookup[ts]:
            # To verify title, we need to fetch the instance
            items = log.get("items") or []
            if not items:
                continue
                
            instance_id = items[0].get("instanceId")
            if not instance_id:
                continue
                
            instance = fc.folio_get(f"/inventory/instances/{instance_id}")
            folio_title = instance.get("title", "Unknown")
            
            if folio_title == title:
                found_match = True
                matches += 1
                break
            else:
                # If titles don't match exactly, maybe it's a sub-title issue?
                # For now, just track it.
                pass
        
        if not found_match:
            errors.append(f"Row {i+1}: No matching instance title '{title}' found for timestamp '{ts}'.")

    # 5. Summary
    print(f"Matches found: {matches}/{len(report_rows)}")
    if errors:
        print("\nDiscrepancies found:")
        for err in errors:
            print(f"  - {err}")
        sys.exit(1)
    else:
        print("\nVerification successful: All report rows match FOLIO audit logs and instance data.")

if __name__ == "__main__":
    latest = get_latest_report()
    if not latest:
        print("No report found in reports/ directory.")
        sys.exit(1)
    verify_report(latest)
